### ISSUE TITLE
axisorder

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataTools2#20]
@ASHISRAVINDRAN 
Do you see a problem changing the axis order to XYZCT?
(I can do it...)

**Comment by ASHISRAVINDRAN** [comment]
It's an arbitrary choice. No problem but will need the changes in a lot of places.
For eg. Here it's still in XYCZT order.
https://github.com/tischi/fiji-plugin-bigDataTools2/blob/master/src/main/java/de/embl/cba/bigDataTools2/saving/SaveImgAsHDF5Stacks.java#L130

https://github.com/tischi/fiji-plugin-bigDataTools2/blob/master/src/main/java/de/embl/cba/bigDataTools2/saving/SaveImgAsTIFFStacks.java#L77

You need to change them too.
More places might need change.

**Comment by tischi** [comment]
I fixed it.
I also fixed it for Tiff planes saving.
And I added tests.
