### ISSUE TITLE
Shearing did not work for new AxisOrder

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataTools2#23]
Fixed: https://github.com/tischi/fiji-plugin-bigDataTools2/commit/e52261e2e15d34f36a47204f3bdf8631ea677e40

Here is the test:
https://github.com/tischi/fiji-plugin-bigDataTools2/blob/master/src/test/java/TestShearTransform.java#L13

@ASHISRAVINDRAN 
Can you also try whether it works from the UI?

**Comment by ASHISRAVINDRAN** [comment]
Tested from UI, works!
