### ISSUE TITLE
ImarisHDF5 Saving

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataTools2#24]
@ASHISRAVINDRAN 
This did not work for me.
Did it ever work?

**Comment by ASHISRAVINDRAN** [comment]
Yes, it used to work in saving. I have a copy of old code before the new axis order. I tested the file writing now and here is the screenshot:

![github_screen](https://user-images.githubusercontent.com/33703127/51804957-8f242f80-2267-11e9-8e4f-569296f9a3ad.jpg)

File names imaris_old are written using code of a older version.
File names imaris_new are wrriten using current version.

I am not sure how to open Imaris data with our UI. So this inference is simply made using the file size.

**Comment by tischi** [comment]
Did you manage to achieve this using this test code?

https://github.com/tischi/fiji-plugin-bigDataTools2/blob/master/src/test/java/TestTHdf5ImarisSaving.java#L11

Because for me it is not saving anything at all..

**Comment by ASHISRAVINDRAN** [comment]
The screenshots were generated via UI.
The problem with the test code was because of Imaris required additional specifications than the ones loaded as default. :) 
So now the files are being written but still, the issue of file size exists as in the screenshot.

**Comment by ASHISRAVINDRAN** [comment]
Fixed and tested in FIJI. Closing issue.
