### ISSUE TITLE
HDF5 loading issue

### ISSUE THREAD

**Issue by ASHISRAVINDRAN** [tischi/fiji-plugin-bigDataTools2#27]
Loading non-calibrated H5 files throws NPE because default voxel sizes are not set.

**Comment by tischi** [comment]
I fixed it like this: 
(uppermost line in your browser-window when you click on below link)
https://github.com/tischi/fiji-plugin-bigDataTools2/commit/5095877c94707b580675ddef454f387211474f8e#diff-25561654723334da4989c35d48e3d4a6R40

**Comment by ASHISRAVINDRAN** [comment]
Works now! Closing the issue.
