### ISSUE TITLE
scope and name

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataTools2#3]
What about:

BigDataConverter

I think that limits nicely the scope, which is good in terms of:
https://en.wikipedia.org/wiki/Single_responsibility_principle

**Comment by ASHISRAVINDRAN** [comment]
Renamed DataStreamingTools class to BigDataConverter. Closing the issue.
Ref: 'https://github.com/tischi/fiji-plugin-bigDataTools2/commit/15f2d42883b4866cb494a89be87abe7f44173e8e'
