### ISSUE TITLE
progress report for saving

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataTools2#8]

**Comment by ASHISRAVINDRAN** [comment]
![newsavewindow](https://user-images.githubusercontent.com/33703127/50386580-f8a1a300-06e9-11e9-9181-2f838a404023.JPG)

I have introduced progress bar in Save Menu itself. This took some time but I think its worth. Simply introducing status bar in ImageJ won't be enough and neat when saving multiple views. Now the user can minimize the save menu window and do other processes(if computing power allows) and check the progress whenever the user wants.  This progress bar auto appears when *Save* button is clicked and auto disappears when save is completed or when *Stop Saving* button is pressed
NB: The progress information is still taken from *MonitorThreadPoolStatus* class. Hence the new progress bar won't show any fine-grained information more than that is shown by the logger.

**Comment by ASHISRAVINDRAN** [comment]
Closing the issue...
