### ISSUE TITLE
time range selection from cropping

### ISSUE THREAD

**Issue by tischi** [tischi/fiji-plugin-bigDataTools2#9]

**Comment by ASHISRAVINDRAN** [comment]
![capture](https://user-images.githubusercontent.com/33703127/50640473-437eae80-0f65-11e9-914b-a1fff5daea5e.JPG)


Time range selection is enabled in Crop Functionality.
You may test and close the issue! :)

**Comment by ASHISRAVINDRAN** [comment]
Time range selection has a bug when time `t min` is non zero value. Cropping internally works fine however when its up for rendering, somewhere in the BDV jars, the line:  
`Util.getTypeFromInterval( source.getSource( 0, 0 ) )` 
throws NPE as `source.getSource(t: 0, level: 0 )` doesn't exist for t =0.
Thanks @haesleinhuepf  for bringing up this in the video!

**Comment by ASHISRAVINDRAN** [comment]
Fixed this by doing Views.zeroMin(...) on the cropped RAI.

**Comment by tischi** [comment]
Ok, makes sense, i think.
